### ISSUE TITLE
not an issue - question on  Value 'sm_86' is not defined for option 'gpu-architecture'

### ISSUE THREAD

**Issue by johndpope** [dbkinghorn/NGC-TF1-nvidia-examples#1]
https://www.pugetsystems.com/labs/hpc/How-To-Install-TensorFlow-1-15-for-NVIDIA-RTX30-GPUs-without-docker-or-CUDA-install-2005/

when I followed all your steps to get 3090 working on existing  - 
I ended up with 
nvcc fatal   : Value 'sm_86' is not defined for option 'gpu-architecture'

I activate environment successfully - run the code - but still bump up with 
Value 'sm_86' is not defined for option 'gpu-architecture'

(I am running zsh - but did do bash terminal / same results)

if I run pip freeze -
I get the following 

I wonder if you could cross reference ? I guess I can do via docker - will post results here later.

absl-py==0.11.0
astor==0.8.1
cached-property==1.5.2
certifi==2020.12.5
chardet==4.0.0
cloudpickle==1.6.0
cycler==0.10.0
dataclasses==0.8
decorator==4.4.2
gast==0.2.2
google-pasta==0.2.0
grpcio==1.34.0
h5py==3.1.0
idna==2.10
imageio==2.9.0
importlib-metadata==3.3.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
Markdown==3.3.3
matplotlib==3.3.3
mock==4.0.3
networkx==2.5
numpy==1.18.5
nvidia-cublas==11.2.1.74
nvidia-cuda-cupti==11.1.69
nvidia-cuda-nvcc==11.1.74
nvidia-cuda-nvrtc==11.1.105
nvidia-cuda-runtime==11.1.74
nvidia-cudnn==8.0.4.30
nvidia-cufft==10.3.0.74
nvidia-curand==10.2.2.74
nvidia-cusolver==11.0.0.74
nvidia-cusparse==11.2.0.275
nvidia-dali-cuda110==0.27.0
nvidia-dali-nvtf-plugin==0.27.0+nv20.11
nvidia-horovod==0.20.2+nv20.11
nvidia-nccl==2.8.2
nvidia-tensorboard==1.15.0+nv20.12
nvidia-tensorflow==1.15.4+nv20.11
nvidia-tensorrt==7.2.1.6
opencv-python-headless==4.4.0.46
opt-einsum==3.3.0
pandas==1.1.5
Pillow==8.0.1
protobuf==3.14.0
psutil==5.8.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.5
PyWavelets==1.1.1
PyYAML==5.3.1
requests==2.25.1
scikit-image==0.17.2
scipy==1.5.4
six==1.15.0
tensorboard @ https://pypi.ngc.nvidia.com/tensorboard/tensorboard-1.15.0-py2.py3-none-any.whl
tensorflow-estimator==1.15.1
termcolor==1.1.0
tifffile==2020.9.3
torch==1.7.1
torchsummaryX==1.3.0
torchvision==0.8.2
typing-extensions==3.7.4.3
urllib3==1.26.2
webencodings==0.5.1
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.4.0

**Comment by dbkinghorn** [comment]
Hi John, sorry I'm late back to you. 

I think you have a path problem. It looks like you still have an older cudatoolkit on your path for cuda 10.x (or even 11.0) which doesn't know about the newer RTX30  GPU's. (ie. sm_86/compute_86)  You need to have cudatoolkit 11.1 or greater on your path. (greater is probably better)
I know it's a mess!  This is why I'm so sold on using containers!   I wrote up this post to help folks that cannot for whatever reason use containers. It's the TF build that NVIDIA puts in their container.  It's a messy pip install since their stuff is not on PyPi

The really messy part is that not everything is isolated to the conda env. I'm using that mostly for the Python 3.6. The NVIDIA stuff is unfortunately not on PyPi which is why that index is being installed under $HOME/.local/share ...

If you have other cuda stuff on your PATH or LD_LIBRARY_PATH (even system default stuff) then you need to get the newer stuff "in front of" that.

**Comment by johndpope** [comment]
I solved this with cuda 11.2 toolkit and 460 driver. Thanks
